name: Daily Scraper

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests beautifulsoup4 pandas

      - name: Run Scraper
        run: python scraper.py

      - name: Push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/kirpekar/sacca-scraper.git
          git add .
          git commit -m "Update scraped data" || echo "No changes to commit"
          git push origin main
