name: Daily Scraper

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests beautifulsoup4 pandas

      - name: Run Scraper
        run: python scraper.py

      - name: Commit & Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add motorcycles.csv
          git commit -m "Update scraped data" || echo "No changes to commit"
          git push
